#!/bin/bash

BDADDR=
DATESTRING=$(date +%Y-%m-%d_%H-%M)

baseline () {
	TIME="${2:-10}"
	echo "Waiting for $TIME seconds"
	sleep "$TIME"
	echo "Finished waiting"
}

receive () {

    DEST=$1
    # kill old instance
    pkill obexd
    /usr/libexec/bluetooth/obexd -a -n -r "${DEST}" &
    OBEXD_PID=$!

	    while read -r line; do
			if [[ $line =~ \"complete\" ]]; then
		 		echo "Transfer completed"
				kill $OBEXD_PID
				exit 0
		    fi
	    done < <(dbus-monitor --session "type='signal',sender='org.bluez.obex',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged'" )
	echo "Finished receive"
}

send () {
	echo "Sleeping for 5"
	sleep 5
	echo "Transmitting file using bt-obex"
	bt-obex -p "${BDADDR}" random-data.txt
	echo "Sent file and sleep again"
	sleep 5
}


OBEX_DIR=$(pwd)/obex-receive
if [ ! -d "$OBEX_DIR" ]; then
  echo "$OBEX_DIR does not exist. Creating."
  mkdir -p "$OBEX_DIR"
fi

SEND_FILE=$(pwd)/random-data.txt
if [ ! -f "$SEND_FILE" ]; then
	echo "$SEND_FILE does not exist. Creating one using dd."
	dd if=/dev/urandom of="$SEND_FILE" bs=1M count=2
fi

sudo btmon -w "${DATESTRING}" > /dev/null &
BTMON_PID=$!

case "$1" in
    h|\?)
        echo "Usage: $0 [-v] [-n name]"
        exit 0
        ;;
    send)
	send
        ;;
    receive)  
        receive "$OBEX_DIR"
        ;;
    baseline)
	    baseline "$1"
	    ;;
esac

kill $BTMON_PID

